name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: package repository
        run: |
          zip -9r code.zip . -x '.git/*'
      - name: create snapshot release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: snapshot-${{ github.run_number }}
          files: code.zip
